version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'gantry-ml/aws-assume-role-in-current-account']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"